IITbazaar/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
#from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
   # url(r'^profiles/', include('accounts.urls', namespace='accounts')),
    path('market/',include('market.urls')),
    url(r'^shopping_cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^accounts/', include('accounts.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/market/', permanent=True)),
]

'''
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]
'''

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.conf.urls import url
from . import views
from .views import my_profile

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^profile/$', my_profile, name='my_profile'),
]

market/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .views import product_list, category_list

app_name = 'market'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', product_list, name='products'),
    #path('results/', search, name='search'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('categories/', category_list, name='categories'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    path('sellers/', views.SellerListView.as_view(), name='sellers'),
    path('seller/<int:pk>', views.SellerDetailView.as_view(), name='seller-detail'),
]

accounts/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User
from market.models import Product
from django.dispatch import receiver


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    user_products = models.ManyToManyField(Product, blank=True)
    #stripe_id = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.user.username


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout
from django.contrib.auth.models import User
from shopping_cart.models import Order
from .models import Profile


# Create your views here.

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  now log the user in
             login(request, user)
             return redirect('market:index')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            return redirect('market:index')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    logout(request)
    return redirect('market:index')

def my_profile(request):
	my_user_profile = Profile.objects.filter(user=request.user).first()
	my_orders = Order.objects.filter(is_ordered=True, owner=my_user_profile)
	context = {
		'my_orders': my_orders
	}

	return render(request, "accounts/profile.html", context)

accounts/templates/accounts/login.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base_generic.html' %}

{% block content %}

<table class="table table-hover table-bordered text-center">
      <tr class="text-center">
        <th>Date Ordered</th>
        <th>Reference Code</th>
        <th>Items</th>
        <th>Price</th>
      </tr>
      {% for order in my_orders %}
        <tr>
          <td>{{ order.date_ordered }}</td>
          <td>{{ order.ref_code }}</td>
          <td>
        	{% for item in order.items.all %}
        		{{ item.product.name }}
      		{% endfor %}
      	  </td>
          <td>Rs.{{ order.get_cart_total }}</td>

        </tr>
      {% empty %}
        <tr>
          <td colspan= 4> You have no orders.</td>
        </tr>
      {% endfor %}

      <tr>
        <td colspan=4>
          <a href="{% url 'market:products' %}" class="btn btn-warning pull-left">
            {% if not order %}Continue Shopping{% else %}Add Items to Cart {% endif %}
          </a> 
        </td>
      </tr>
    </table>

{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base_generic.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}