IITbazaar/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf.urls import url
#from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
   # url(r'^profiles/', include('accounts.urls', namespace='accounts')),
    path('market/',include('market.urls')),
    url(r'^shopping_cart/', include('shopping_cart.urls', namespace='shopping_cart')),
    url(r'^accounts/', include('accounts.urls')),
]

#Add URL maps to redirect the base URL to our application
from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='/market/', permanent=True)),
]

'''
#Add Django site authentication urls (for login, logout, password management)
urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]
'''

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

market/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from .views import product_list, category_list

app_name = 'market'

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', product_list, name='products'),
    #path('results/', search, name='search'),
    path('product/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'),
    path('categories/', category_list, name='categories'),
    path('category/<int:pk>', views.CategoryDetailView.as_view(), name='category-detail'),
    path('sellers/', views.SellerListView.as_view(), name='sellers'),
    path('seller/<int:pk>', views.SellerDetailView.as_view(), name='seller-detail'),
]

shopping_cart/urls.py
from django.conf.urls import url

from .views import (
    add_to_cart,
    delete_from_cart,
    order_details,
    checkout,
    success,
    process_payment,
    update_transaction_records,
)

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<item_id>[-\w]+)/$', add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', order_details, name="order_summary"),
    url(r'^success/$', success, name='purchase_success'),
    url(r'^item/delete/(?P<item_id>[-\w]+)/$', delete_from_cart, name='delete_item'),
    url(r'^checkout/$', checkout, name='checkout'),
    url(r'^payment/(?P<order_id>[-\w]+)/$', process_payment, name='process_payment'),
    url(r'^update-transaction/(?P<order_id>[-\w]+)/$', update_transaction_records,name='update_records'),    
]        

market/models.py
from __future__ import unicode_literals

from django.db import models
from django.conf import settings
from django.utils import timezone
from django.urls import reverse # Used to generate URLs by reversing the URL patterns
from phonenumber_field.modelfields import PhoneNumberField

# Create your models here.

'''
class ProductManager(models.Manager):
    def active(self, *args, **kwargs):
        # Post.objects.all() = super(PostManager, self).all()
        return super(ProductManager, self).filter(timestamp__lte=timezone.now())
'''
class Category(models.Model):
    name = models.CharField(max_length=50, help_text='Product category')

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this category."""
        return reverse('market:category-detail', args=[str(self.id)])

class Seller(models.Model):
    name = models.CharField(max_length=60)
    phone = PhoneNumberField(null=False, blank=True, unique=True)
    address = models.TextField(max_length=500, null=True)

    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this seller."""
        return reverse('market:seller-detail', args=[str(self.id)])


class Product(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    description = models.TextField(max_length=1000, help_text='brief description of the product', blank=True)
    image = models.ImageField(default='default.png',blank=True)
    seller = models.ForeignKey(Seller, on_delete=models.SET_NULL, null=True, blank=True)
    category = models.ManyToManyField(Category, help_text='Categories for this product', blank=True)
    #available = models.BooleanField(default=True)
    stock = models.PositiveIntegerField(default=1)
    # Manager
    #objects = ProductManager()


    def __str__(self):
        """String for representing the Model object."""
        return self.name

    def get_absolute_url(self):
        """Returns the url to access a detail record for this product."""
        return reverse('market:product-detail', args=[str(self.id)])

market/views.py
#from __future__ import unicode_literals

from django.shortcuts import render
#from django.conf import settings
#from django.utils import timezone

from django.db.models import Q
from shopping_cart.models import Order
from market.models import Product, Seller, Category
from accounts.models import Profile
from django.contrib.auth.models import User
from django.contrib import auth

# Create your views here.

def index(request):
    num_products = Product.objects.all().count()
    num_sellers = Seller.objects.all().count()
    num_categories = Category.objects.all().count()

    context = {
        'num_products': num_products,
        'num_sellers': num_sellers,
        'num_categories': num_categories,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)

from django.views import generic

def product_list(request):
    object_list = Product.objects.all()

    if 'search' in request.GET:
        search_item = request.GET['search']
        object_list = Product.objects.filter(name__icontains=search_item)
    '''
    queryset_list = Product.objects.active()
    if request.user.is_staff or request.user.is_superuser:
        queryset_list = Product.objects.all()

    query = request.GET.get("q")
    if query:
        queryset_list = queryset_list.filter(name__icontains=query)
    '''

    if request.user.is_authenticated:
        filtered_orders = Order.objects.filter(owner=request.user.profile, is_ordered=False)
        current_order_products = []
        if filtered_orders.exists():
            user_order = filtered_orders[0]
            user_order_items = user_order.items.all()
            current_order_products = [product.product for product in user_order_items]

        context = {
            'product_list': object_list,
            'current_order_products': current_order_products,
        }

    else:
        context = {
            'product_list': object_list,
        }

    return render(request, "market/product_list.html", context)

class ProductDetailView(generic.DetailView):
    model = Product

class SellerListView(generic.ListView):
    model = Seller
    #paginate_by = 10

class SellerDetailView(generic.DetailView):
    model = Seller

def category_list(request):
    object_list = Category.objects.all()

    if 'search' in request.GET:
        search_item = request.GET['search']
        object_list = Category.objects.filter(name__icontains=search_item)

    context = {
            'category_list': object_list,
        }

    return render(request, "market/category_list.html", context)

class CategoryDetailView(generic.DetailView):
    model = Category



'''
def search(request):
    query = request.GET.get('q')
    results = Product.objects.filter(Q(name__icontains=query))
    object_list = Product.objects.all()
    #object_list = Product.objects.all()
    if request.user.is_authenticated:
        filtered_orders = Order.objects.filter(owner=request.user.profile, is_ordered=False)
        current_order_products = []
        if filtered_orders.exists():
            user_order = filtered_orders[0]
            user_order_items = user_order.items.all()
            current_order_products = [product.product for product in user_order_items]

        context = {
            'product_list': object_list,
            'current_order_products': current_order_products,
        }

    else:
        context = {
            'product_list': results,
        }

    return render(request, "market/product_list.html", context)
'''
    

market/templates/market/category_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>{{ category.name }}</h1>
    
    <div style="margin-left:20px;margin-top:20px">
        <h4>Products</h4>
        
        <dl>
        {% for product in category.product_set.all %}
          <dt><a href="{% url 'market:product-detail' product.pk %}">{{product}}</a> (Rs.{{ product.price }}/-)</dt>
        {% endfor %}
        </dl>
        
    </div>
{% endblock %}

market/templates/market/category_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Categories</h1>
  <form method="GET" action="">
    <input type="search" name="search" placeholder="Search categories" value="{{ search_term }}"/>
    <input type="submit" value="Search"/>
  </form>
  {% if category_list %}
  <ul>
    {% for category in category_list %}
      <li>
        <a href="{{ category.get_absolute_url }}">{{ category.name }}</a>
    </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No categories currently</p>
  {% endif %}       
{% endblock %}

market/templates/market/product_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1> {{ product.name }}</h1>
    <p><img src="{{ product.image.url }}"/></p>
    <p><strong>Price:</strong> Rs.{{ product.price }}/-</p>
    <p><strong>Category:</strong> {% for category in product.category.all %} {{ category }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
   
    <p><strong>Description:</strong> {{ product.description }}</p>
    <p><strong>Seller:</strong> <a href="{% url 'market:seller-detail' product.seller.pk %}">{{ product.seller }}</a></p>
    <p>
        {% if user.is_authenticated %}
            {% if product in user.profile.user_products.all %}
                
                You own this
                
                {% elif product in current_order_products %}
                <a href="{% url 'shopping_cart:order_summary' %}" class="btn btn-warning">Go to Cart</a>
                
                {% else %}
                <a href="{% url 'shopping_cart:add_to_cart' product.id %}" class="btn btn-warning">Add to Cart</a>
                {% endif %}
        {% else %}
            Login to buy!        
        {% endif %}        
    </p>
{% endblock %}
 

market/templates/market/product_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Products</h1>
  <form method="GET" action="">
    <input type="search" name="search" placeholder="Search products" value="{{ search_term }}"/>
    <input type="submit" value="Search"/>
  </form>
  {% if product_list %}
  <ul>
    {% for product in product_list %}
      <li>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a> (Rs.{{product.price}}/-)
        <p><img src="{{ product.image.url }}"/></p>
    <p><strong>Price:</strong> Rs.{{ product.price }}/-</p>
    <p><strong>Category:</strong> {% for category in product.category.all %} {{ category }}{% if not forloop.last %}, {% endif %}{% endfor %}</p>
   
    <p><strong>Description:</strong> {{ product.description }}</p>
    <p><strong>Seller:</strong> <a href="{% url 'market:seller-detail' product.seller.pk %}">{{ product.seller }}</a></p>
    <p>
        {% if user.is_authenticated %}
            {% if product in user.profile.user_products.all %}
                
                You own this
                
                {% elif product in current_order_products %}
                <a href="{% url 'shopping_cart:order_summary' %}" class="btn btn-warning">Go to Cart</a>
                
                {% else %}
                <a href="{% url 'shopping_cart:add_to_cart' product.id %}" class="btn btn-warning">Add to Cart</a>
                {% endif %}
        {% else %}
            Login to buy!        
        {% endif %}        
    </p>
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no products currently available in the market.</p>
  {% endif %}       
{% endblock %}

market/templates/market/products.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Products</h1>
  {% if all_products %}
  <ul>
    {% for product in all_products %}
      <li>
        <a href="{{ product.get_absolute_url }}">{{ product.name }}</a> (Rs.{{product.price}}/-)
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no products currently available in the market.</p>
  {% endif %}       
{% endblock %}

market/templates/market/seller_detail.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>{{ seller.name }}</h1>
    <p><strong>Contact Number:</strong> {{ seller.phone }}</p>
    <p><strong>Address:</strong> {{ seller.address }}</p>
    <div style="margin-left:20px;margin-top:20px">
        <h4>Products</h4>
        
        <dl>
        {% for product in seller.product_set.all %}
          <dt><a href="{% url 'market:product-detail' product.pk %}">{{product}}</a> (Rs.{{ product.price }}/-)</dt>
        {% endfor %}
        </dl>
        
    </div>
{% endblock %}

market/templates/market/seller_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Seller List</h1>
  {% if seller_list %}
  <ul>
    {% for seller in seller_list %}
      <li>
        <a href="{{ seller.get_absolute_url }}">{{ seller.name }}</a> 
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>No sellers currently</p>
  {% endif %}       
{% endblock %}